### ISSUE TITLE
Reason why updateUsable hook needs to be implemented

### ISSUE THREAD

**Issue by jeffhertzler** [LevelbossMike/ember-statecharts#268]
> WARNING: A change to passed `args` or a local state change triggered an update to a `useMachine`-usable. This is currently unsupported and should probably be handled explicitly in your xstate-machine. If you feel this is necessary behavior that should be supported by `ember-statecharts` please raise this as an issue and provide an example of what you are trying to do.

Here's a quick example of why this needs to be implemented: https://codesandbox.io/s/sharp-water-uhcvv?file=/app/templates/application.hbs

Components are not torn down and recreated when transitioning from one param on a route to another. As far as I know, I have no control here to add anything to the machine to deal with this.

**Comment by LevelbossMike** [comment]
Hi @jeffhertzler and thanks for raising this issue.

I thought about this use-case but it is not entire clear to me what we should be doing in a situation like this.

Right now there is a way to handle this and the way to do so is to model this change of the model explicitly in the statechart.

In your example:

```js
import { Machine, assign } from 'xstate';

const myMachine = Machine({
  id: "my-machine",
  initial: "idle",
  states: {
    idle: {
      on: {
         ARGS_CHANGED: {
            target: 'idle',
            actions: ['resetContextForArgsChange']
          }
      }
    },
    other: {}
  }
}, {
  actions: {
     resetContextForArgsChange: assign({
       id: (context, { id }) => id
     })
  }
});
```

And in your template:

```hbs
<div {{did-update this.handleIdUpdate @id}}>
  {{!-- the rest of the template--}}
</div>
```
You'd need to send the event change on `did-update`:

```js
export default class Statechart extends Component {
  // ...
  @action
  handleIdUpdate(_element, [id]) {
    this.statechart.send('ARGS_CHANGED', { id })
  }
}
```

This looks super complicated at first but is actually the best we can do without defining a 'magic' event called (I don't know how to call it but for now) 'ARGS_CHANGED' that we send to the intialized xstate interpreter that is being started when you use `useMachine`.

I'm not totally against creating functionality like this but I'm not totally convinced that this is the best approach in a situation like this. Imo this is something that needs to be modeled explicitly in your statechart because this is actual behavior that you are modeling - a passed in `args` changed that is relevant for defining the context of the machine.

You would even need to model this explicitly if we sent a magic `ARGS_CHANGED` event because there's no way to do anything via the statechart without sending an event to it - which is a feature not a bug.

From what I understood from our discussion in discord reseting the machine to the initial state would be good enough in your particular use case - I doubt this is the case for all use-cases though - that's why I'm conviced this needs to be modeled explicitly.

I agree that using `did-update` in this scenario seems pretty hacky. I personally don't like this pattern especially in situation where you are dealing with a renderless component that usually wouldn't have a wrapper div. This means that just to send an update you sometimes have to create a hidden div that is just there for sending update events. Example:

```hbs
{{!-- fancy-provider.hbs --}}
{{yield
  complexValue=this.thisComponentOnlyProvidesAComplexValue
}}
<div class="hidden" {{did-update this.handleArgsChange @argA @argB, @argC}}></div>
```

Again - I'm not stoked about this approach but at least it's better than `didReceiveAttrs` because you have control over when to send this event based on what `args` changed.

I also understand that this looks like it's going against `@use` in general. `@use` was created for exactly this use case to not need to use a render-modifier to handle a situation like this. I get this - but again it's kind of hard to decide how to handle this the best way possible. Do we really want to create a "magic" event that our users just need to know about? Is that really better than sending an event explicitly based on `did-update`? Won't this break down in a situation where we not only want to transition into a different state if args change but some other internal event happens?

I could imagine a scenario where this is optionally configurable when using `useMachine`. Maybe `useMachine(yourMachine, { handleUsableUpdates: true })`. I still think this feels pretty clunky from an api perspective but maybe this is the way to go here.

## A note on renderless things like services

I doubt this is really an issue with services but only with components. Service aren't tied to the render context at all so they won't run into this issue.

cc
@pangratz @NullVoxPopuli @robertpbaxter

**Comment by LevelbossMike** [comment]
@jeffhertzler @NullVoxPopuli @robertpbaxter After looking into this a bit it seems pretty tricky to send a "magic" event based on the fact that `args` changed that were passed to `useMachine`. The arguments passed to `updateUsable` from what I understand are what gets returned when `useMachine` would have been run with the updated `args`.

Based on that it gets pretty tricky to know what to send to the magic `ARGS_UPDATED`-event that I discussed previously. We might be able to make it work by passing an optional function to `useMachine` which return value gets send to the interpreter. This at least is as explicit as possible and pretty flexible. It's still pretty verbose for my taste but maybe that's power user functionality that people might want opt-in using.

Example:

```js
const counterMachine = Machine({
  initial: 'active',
  states: {
    active: {
      on: {
         INCREMENT: {
           target: 'active',
           actions: [
             assign({
               count: (context) => context.count + 1;
              })
           ]
         },
         COUNT_ARG_CHANGED: {
           target: 'active',
           actions: [
             assign({
               count: (context, { count }) => context.count = count;
             }
           ]
         }
       }
     }
  }
});
/*
  This function will be called when args passed to `useMachine`, `withConfig` or `withContext`
  were changed - we save the complete objects passed to these functions and the return value of this function would be
  send to the interpreterService we already started by accessing `useMachine` before
  
  args: { machine: Machine | MachineConfig, config: MachineConfig, context: MachineContext }
*/
function updateUsable({ context }) {
  // this is a valid `send` function signature that xstate understands
  return { type: 'COUNT_ARG_CHANGED', count: context.count };
}

export default class Counter extends Component {
   @use statechart = useMachine(counterMachine, { updateUsable })
      .withContext({
        count: this.args.count
       });
}
```

**Comment by scottmessinger** [comment]
Conceptually, I really like the `updateUsable` solution. I might change it to something more generic like, `UPDATE_FROM_ARGS`, but it feels right to me that there's a function that's called when args change and that function returns a `send` function that triggers a machine action.

**Comment by NullVoxPopuli** [comment]
First, some background and context to the overall resistence to the proposed alternative to "just supporting updates" and why they feel hacky:

Triggering updates from the template for non-element behavior is imperitive, which ends up being counter to the declarative nature that Octane paradigms are trying to push us towards.  `@ember/render-modifiers` don't have any semantic or declarative correlation with the intent behind modifiers -- as "Modifiers" are short "Element Modifiers" -- for elements. ;D
It's the same story for _effecting_ helpers --  `ember-render-helpers`. Both `@ember/render-modifiers` and `ember-render-helpers` are meant to be temporary solutions for _transition_ to Octane -- and while we wait for `@use`ables -- once the usables RFC is accepted and lands, I think there will be much more coherance on this topic, as it all kind of word of mouth right now and leaves everyone in limbo trying out weird awkward things like render-modifiers / render-helpers.

> Explicit vs Implicit Updates to the state machine's args

This is ultimately the question at hand here, I think we really only have one option, given the above look at the future and what I see as the intent of usables, modifiers, etc:

> I could imagine a scenario where this is optionally configurable

I'd like to propose a slightly different, maybe more "batteries included" approach.

The gist is that useMachine will _always_ respond to updates to the args passed to it -- _however_, we should throw an assertion in development if an update is triggered and no transition name is passed (this could be `ARGS_CHANGED`, or whatever you wish). If the args to useMachine never change, the assertion willl never throw.

```ts
export default class NonComponentClass {
   @use statechart = useMachine(transferSessionMachine, { changeEvent: 'SESSION_CHANGED' })
      .withContext({
        sessionInfo: this.sessionInfo, // could change if the user logs out while this machine is in the middle of stuff
       });
}
```

In this example, when `this.sessionInfo` changes, the `useMachine` code will `send` a transition to the machine, with the event `SESSION_CHANGED`, with all the args spread into the event, e.g.: `{ type: 'SESSION_CHANGED', sessionInfo }`.

Implementation wise, this does mean that we need to do some gymnastics, the update / destroy hooks -- per the spec: https://github.com/emberjs/rfcs/blob/use-and-resources/text/0567-use-and-resources.md#resourcemanager, they receive the same "bucket" of stuff for create. Which means, that we'll need entangle anything passed to `withContext` or the other `with*` methods with the "bucket" passed to create so that update is passed the all the args.

We should probably also implement the `destroy` hook, with a similar `destroyEvent`, maybe without throwing an assertion though, as not all machines will _need_ cleanup. I have a usecase for cleanup, because I have machines creating websocket connections.

**Comment by LevelbossMike** [comment]
To people that are interested in this functionality:

I created a PR that allows users to react to changes with the usable directly.

The PR can be found here: https://github.com/LevelbossMike/ember-statecharts/pull/270

**Comment by jeffhertzler** [comment]
Thank you! This is great.
