### ISSUE TITLE
Editor page in documentation does not work

### ISSUE THREAD

**Issue by MichalBryxi** [LevelbossMike/ember-statecharts#320]
Screenshot of what I get. I don't think that the first 404 means anything.

![Screenshot 2020-10-27 at 20 51 39](https://user-images.githubusercontent.com/847473/97360565-a65dda00-189e-11eb-83a9-160ba8719ca1.png)

**Comment by LevelbossMike** [comment]
Thanks for raising this issue. The links to the editor page are a leftover from previous versions and i seemed to have missed to remove some links to it. 

Instead of maintaining our own editor we opted to tell people to use the [XState visualizer](https://xstate.js.org/viz/) directly instead. It is the official solution and supports all xstate features. we didn’t feel like it s a good investment to maintain our own visualizer. 

I’ll remove the remaining links today - I thought i changed all of them to link to the xstate visualizer already :/. If you want to try out the old visualizer you can use the versions Dropdown-Menu in the docs. I think versions <=0.9 will still show it.

**Comment by MichalBryxi** [comment]
No worries. Was just reading end-to-end through the docs and noticed this. I can use the the official Xstate visualizer no problem :)

**Comment by LevelbossMike** [comment]
For anybody who wants to play around with our custom editor - https://ember-statecharts.com/versions/v0.8.2/editor

This version works fairly well but is lacking support for certain XState features. Stay tuned for a better statechart authoring experience in the near future.

Closing as this isn't really an issue with ember-statecharts in general.
