### ISSUE TITLE
Max call size exceeded render issue with entry actions

### ISSUE THREAD

**Issue by lllama** [LevelbossMike/ember-statecharts#350]
The following application controller will fail to render:
```js
import Controller from '@ember/controller';
import { action } from '@ember/object';
import { matchesState, useMachine } from 'ember-statecharts';
import { use } from 'ember-usable';

export default class ApplicationController extends Controller {
  @use statechart = useMachine({
    initial: 'idle',
    states: {
      idle: {
        entry: ['tossCoin'],
        on: {
          HEADS: 'heads',
          TAILS: 'tails',
        },
      },
      heads: {},
      tails: {},
    },
  }).withConfig({
    actions: {
      tossCoin: this.tossCoin,
    },
  });

  @matchesState('heads')
  isHeads;
  @matchesState('tails')
  isTails;

  @action tossCoin() {
    if (Math.floor(Math.random() * 2)) {
      this.statechart.send('HEADS');
    } else {
      this.statechart.send('TAILS');
    }
  }
}
```

With the following template: 
```hbs
{{page-title 'Statechart Test'}}
{{#if this.isHeads}}
  IT'S HEADS!!
{{else}}
  IT'S TAILS!!
{{/if}}
{{outlet}}
```

**Comment by lllama** [comment]
Looks like moving the `send`s to a `setTimeout` will 'fix' the issue:
```js
import Controller from '@ember/controller';
import { action } from '@ember/object';
import { matchesState, useMachine } from 'ember-statecharts';
import { use } from 'ember-usable';

export default class ApplicationController extends Controller {
  @use statechart = useMachine({
    initial: 'idle',
    states: {
      idle: {
        entry: ['tossCoin'],
        on: {
          HEADS: 'heads',
          TAILS: 'tails',
        },
      },
      heads: {},
      tails: {},
    },
  }).withConfig({
    actions: {
      tossCoin: this.tossCoin,
    },
  });

  @matchesState('heads')
  isHeads;
  @matchesState('tails')
  isTails;

  @action tossCoin() {
    if (Math.floor(Math.random() * 2)) {
      setTimeout(() => {
        this.statechart.send('HEADS');
      }, 10);
    } else {
      setTimeout(() => {
        this.statechart.send('TAILS');
      }, 10);
    }
  }
}

```

**Comment by LevelbossMike** [comment]
I think you are running into a similar issue like discussed here on discord:

https://discord.com/channels/480462759797063690/488717827323461632/801475119791865876

I.e. if you want to trigger an effect on component initialization you need to schedule sending the event that triggers the effect - best done on the `actions`-queue otherwise the glimmer-vm will yell at you.

`setTimeout` only fixes the symptom. A better way to do this is this:

```js
export default class MyComponent extends Component {
  constructor() {
     super(...arguments);
     schedule('actions', () => this.statechart.send('TOSS'))
  }
}

```
or use a `did-insert` modifier to trigger the first coin-toss.

It is kind of unfortunate that the glimmer-vm behaves that way and we need to schedule here but further detail about why it is doing that can be found in the linked discord-chat.

The discussion came up when I myself encountered a similar thing when I tried to register a child-component on its parent in its constructor. [original question](https://discord.com/channels/480462759797063690/488717827323461632/801008097090732054)

I don't think this is an issue with ember-statecharts but more with the way Glimmer-VM works, i.e. there's nothing for us to "fix". Thus I'm closing the issue. If you feel differently please let me know - Happy to reopen if this is really an issue with ember-statecharts itself.
