### ISSUE TITLE
interpreterFor types are off

### ISSUE THREAD

**Issue by knownasilya** [LevelbossMike/ember-statecharts#370]
```ts
@use statechart = interpreterFor(
    useMachine(entityMachine)
  )
    .withContext({
    })
```

Returns the following TS error:

```
Property 'withContext' does not exist on type 'InterpreterUsable<any, any, any, { value: any; context: any; }>'.ts(2339)
```

**Comment by LevelbossMike** [comment]
The way that you invoke `interpreterFor` is incorrect. You would need to use `interpreterFor` like this:

```ts
@use statechart = interpreterFor(
    useMachine(entityMachine)
    .withContext({
       // ...
    })
  )
```

`interpreterFor` is a typecast function that only exists to make typescript happy because it does not deal well with decorators - The value of the usable is different to the definition of the usable because of what `@use` does.

**Comment by knownasilya** [comment]
That worked, thanks!
