### ISSUE TITLE
Adding a context helper

### ISSUE THREAD

**Issue by akfernun** [LevelbossMike/ember-statecharts#371]
I've often found myself adding lots of `getters` in my ember components for extracting data out of the xstate context object. What are your thoughts about maybe adding a decorator helper for extracting data out of context. I envision the API maybe looking something like 

```
export default class MyComponent extends Component {
   @context('first_name') firstName;
   @context lastName;
   ....
}
```

Something like that. What are your thoughts? I could help PR this change as well!

**Comment by sukima** [comment]
If it were me I would say the context is being abused. My understanding and how I use context is that it is for _indefinite_ states. States that can't fit within the confines of _finite_ states. For example a counter used to make a single state enterable only five times. To do that with finite states would require five unique states in the machine. But with a context you can simply increment a counter each time you enter one state and have a guard check the counter.

Another consideration I believe in is that context should be something that could be serialized so that when and if you needed to save, dehydrate, and rehydrate later you can. If you use complex things like classes the rehydration process would be far more taxing.

And lastly I found in my experience when I litter the context with data that has dependencies outside the state machine that it really over complicates my code. If instead I used actions and those actions manipulated data outside the state machine it was far easier to reason about. Leaving the context specific to data that the state machine directly uses as part of its design was fine and in most cases this was plain simple types like numbers, strings, and booleans.

It allowed me to literally pull the whole machine (context and all) out of the source and paste it elsewhere. I could reuse machines between front end frameworks, or in the backend, or in the visualizer. Leaving the undefined actions/guards/services in name only and hook them up as needed.

I truly believe you can create state charts that are **not** tightly coupled to the frame work components using them. And one of the steps to the decoupled modular design is to make the context simple and not carry complex and implementation specific data. It should not be a message passing service but a brain telling the body what to do.

**Comment by akfernun** [comment]
@sukima, these are great points and thanks for writing that out. One question I do have though is that this particular issue is about having a helper that will pull values out of `context`. That said, it's not necessarily implying anything about _what_ people are putting in it. So regardless of whether or not context is being abused, is it fair to say that we _all_ need to pull values out of it, and this is suggestion would make it easier to do that?

**Comment by LevelbossMike** [comment]
@akfernun I personally would suggest to just create a getter to get to the state. If need be you can create a decorator like that yourself, but currently I'm not a fan of expanding the api surface of ember-statecharts for this. It doesn't feel like something that is related to the functionality that ember-statecharts provides but more of a convenience helper.

Regarding what @sukima pointed out - and I'm just leaving this here for people interested in the topic - I agree that pulling data in the statechart from the outside isn't the way to go. You want the statechart to manage the context. You can combine statechart state and ephemeral component state in getters but that is rarely necessary in my experience as you then usually run into territory where you are not modeling behavior explicitly anymore.

I'm closing this but please feel free to reopen if you disagree with the reasoning.
